// Generated by gencpp from file navigation_sim/AddTwoInts.msg
// DO NOT EDIT!


#ifndef NAVIGATION_SIM_MESSAGE_ADDTWOINTS_H
#define NAVIGATION_SIM_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <navigation_sim/AddTwoIntsRequest.h>
#include <navigation_sim/AddTwoIntsResponse.h>


namespace navigation_sim
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace navigation_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation_sim::AddTwoInts > {
  static const char* value()
  {
    return "d431cae597499d244ef1c576e21358c8";
  }

  static const char* value(const ::navigation_sim::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::navigation_sim::AddTwoInts > {
  static const char* value()
  {
    return "navigation_sim/AddTwoInts";
  }

  static const char* value(const ::navigation_sim::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::navigation_sim::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::navigation_sim::AddTwoInts >
template<>
struct MD5Sum< ::navigation_sim::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_sim::AddTwoInts >::value();
  }
  static const char* value(const ::navigation_sim::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_sim::AddTwoIntsRequest> should match
// service_traits::DataType< ::navigation_sim::AddTwoInts >
template<>
struct DataType< ::navigation_sim::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::navigation_sim::AddTwoInts >::value();
  }
  static const char* value(const ::navigation_sim::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation_sim::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::navigation_sim::AddTwoInts >
template<>
struct MD5Sum< ::navigation_sim::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_sim::AddTwoInts >::value();
  }
  static const char* value(const ::navigation_sim::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_sim::AddTwoIntsResponse> should match
// service_traits::DataType< ::navigation_sim::AddTwoInts >
template<>
struct DataType< ::navigation_sim::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::navigation_sim::AddTwoInts >::value();
  }
  static const char* value(const ::navigation_sim::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_SIM_MESSAGE_ADDTWOINTS_H
