// Generated by gencpp from file navigation_sim/multipli2ints.msg
// DO NOT EDIT!


#ifndef NAVIGATION_SIM_MESSAGE_MULTIPLI2INTS_H
#define NAVIGATION_SIM_MESSAGE_MULTIPLI2INTS_H

#include <ros/service_traits.h>


#include <navigation_sim/multipli2intsRequest.h>
#include <navigation_sim/multipli2intsResponse.h>


namespace navigation_sim
{

struct multipli2ints
{

typedef multipli2intsRequest Request;
typedef multipli2intsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct multipli2ints
} // namespace navigation_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation_sim::multipli2ints > {
  static const char* value()
  {
    return "d431cae597499d244ef1c576e21358c8";
  }

  static const char* value(const ::navigation_sim::multipli2ints&) { return value(); }
};

template<>
struct DataType< ::navigation_sim::multipli2ints > {
  static const char* value()
  {
    return "navigation_sim/multipli2ints";
  }

  static const char* value(const ::navigation_sim::multipli2ints&) { return value(); }
};


// service_traits::MD5Sum< ::navigation_sim::multipli2intsRequest> should match
// service_traits::MD5Sum< ::navigation_sim::multipli2ints >
template<>
struct MD5Sum< ::navigation_sim::multipli2intsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_sim::multipli2ints >::value();
  }
  static const char* value(const ::navigation_sim::multipli2intsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_sim::multipli2intsRequest> should match
// service_traits::DataType< ::navigation_sim::multipli2ints >
template<>
struct DataType< ::navigation_sim::multipli2intsRequest>
{
  static const char* value()
  {
    return DataType< ::navigation_sim::multipli2ints >::value();
  }
  static const char* value(const ::navigation_sim::multipli2intsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation_sim::multipli2intsResponse> should match
// service_traits::MD5Sum< ::navigation_sim::multipli2ints >
template<>
struct MD5Sum< ::navigation_sim::multipli2intsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_sim::multipli2ints >::value();
  }
  static const char* value(const ::navigation_sim::multipli2intsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_sim::multipli2intsResponse> should match
// service_traits::DataType< ::navigation_sim::multipli2ints >
template<>
struct DataType< ::navigation_sim::multipli2intsResponse>
{
  static const char* value()
  {
    return DataType< ::navigation_sim::multipli2ints >::value();
  }
  static const char* value(const ::navigation_sim::multipli2intsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_SIM_MESSAGE_MULTIPLI2INTS_H
